spring:
  datasource:
    username: postgres
    password: root
    url: jdbc:postgresql://localhost:5432/markup
  jpa:
    show-sql: true
  liquibase:
    enabled: false

datasets:
  storage:
    location: ./datasets
